// Path: src/contexts/LanguageContext.tsx
"use client";

import React, { createContext, useState, useContext, useEffect } from "react";

// Define supported languages
export type Language = "en" | "th";

// Enhanced translation function type to support parameter interpolation
type TranslationFunction = {
  (key: string): string;
  (key: string, params?: Record<string, string | number>): string;
};

// Define the context type
type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: TranslationFunction;
};

// Create context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

// Interpolation function to replace placeholders
const interpolate = (
  template: string,
  params?: Record<string, string | number>
): string => {
  if (!params) return template;

  return template.replace(/\{(\w+)\}/g, (match, key) => {
    return params[key]?.toString() || match;
  });
};

// Add more comprehensive translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.map": "Map",
    "nav.carpool": "Carpool",
    "nav.community": "Community",
    "nav.profile": "Profile",

    // Map
    "map.search": "Search here...",
    "map.accessibility": "Accessibility",
    "map.accessibility.fully": "Fully Accessible",
    "map.accessibility.partially": "Partially Accessible",
    "map.accessibility.limited": "Limited Access",
    "map.locate.current.location": "Locate my current position",
    "map.current.location": "You are here",
    "map.selected.route": "Selected Route",
    "map.selected.route.description": "Your selected accessible route",
    "map.show.route": "Show Route",
    "map.route.details": "Route Details",

    // Obstacle-related translations
    "obstacle.status.active": "Active",
    "obstacle.status.resolved": "Resolved",
    "obstacle.reported.by": "Reported by: {name} ที่ {number}}",
    "obstacle.reported.date": "Date: {date}",
    "obstacle.last.verified": "Last verified: {date}",
    "obstacle.verify.status.title": "Verify Status",
    "obstacle.verify.status.description":
      "Help keep our data up to date by verifying this obstacle",
    "obstacle.verify.still.present": "Still Present",
    "obstacle.verify.no.longer.present": "Resolved",
    "obstacle.category.sidewalk_issues": "Sidewalk Issue",
    "obstacle.category.permanent_obstacles": "Permanent Obstacle",
    "obstacle.category.temporary_obstacles": "Temporary Obstacle",
    "obstacle.category.connection_issues": "Connection Issue",
    "obstacle.category.safety_issues": "Safety Issue",
    "obstacle.report.title": "Report Obstacle",
    "obstacle.report.details": "Obstacle Details",
    "obstacle.report.category": "Category",
    "obstacle.report.type": "Type of Obstacle",
    "obstacle.report.description": "Description",
    "obstacle.report.submit": "Submit Report",
    "obstacle.category.etc": "Other",

    "ui.select.category": "Select category",
    "ui.select.type": "Select type",
    "obstacle.photos.add": "Add photos",
    "obstacle.photos.click.to.add": "Click to add photos",
    "obstacle.photo.selected": "Selected photo {number}",
    "obstacle.description.placeholder":
      "Describe more details about the obstacle you found...",
    "obstacle.category.other_obstacles": "Other",
    "obstacle.type.other": "Other",

    // Actions
    "action.record.route": "Record Route",
    "action.report.obstacle": "Report Obstacle",
    "action.add.post": "Add Post",

    // Carpool
    "carpool.title": "Carpool",
    "carpool.available.rides": "Available Rides",
    "carpool.my.rides": "My Rides",
    "carpool.from": "From:",
    "carpool.to": "To:",
    "carpool.more.info": "More info",
    "carpool.ride.details": "Ride Details",
    "carpool.vehicle.info": "Vehicle Information",
    "carpool.price.per.seat": "Price per seat",
    "carpool.chat.with.driver": "Chat with Driver",
    "carpool.book.now": "Book Now",
    "carpool.messages": "Messages",
    "carpool.driver": "Driver",
    "carpool.seats.available": "{count} seats available",
    "carpool.date": "Date",
    "carpool.time": "Time",
    "carpool.vehicle.type": "Vehicle Type",
    "carpool.rating": "Rating",

    // Community
    "community.search": "Search here...",
    "community.categories.all": "All",
    "community.categories.guides": "Guides & Tips",
    "community.categories.equipment": "Equipment Reviews",
    "community.categories.stories": "Inspiring Stories",
    "community.categories.news": "News & Events",
    "community.categories.services": "Support Services",
    "community.categories.routes": "Suggested Routes",
    "community.categories.health": "Health & Self Care",
    "community.categories.career": "Career & Work",
    "community.post": "Post",
    "community.create.post": "Create Post",
    "community.share": "Share",
    "community.add.location": "Add location",
    "community.no.posts": "No posts found",
    "community.post.view.details": "View post details",
    "community.post.image.alt": "Post image by {username}",
    "community.user.avatar": "{username}'s avatar",
    "community.post.like": "Like post",
    "community.post.comments": "View comments",
    "community.post.share": "Share post",
    "community.add.comment": "Add a comment...",
    "community.sort.by": "Sort by",
    "community.most.recent": "Most Recent",
    "community.most.liked": "Most Liked",
    "community.most.comments": "Most Comments",
    "community.filter.features": "Accessibility Features",

    // Profile
    "profile.edit": "Edit Profile",
    "profile.routes": "Routes",
    "profile.following": "Following",
    "profile.followers": "Followers",
    "profile.wheelchair.info": "Wheelchair Information",
    "profile.tabs.all": "All Routes",
    "profile.tabs.recorded": "Recorded",
    "profile.tabs.saved": "Saved",
    "profile.settings": "Settings",

    // Wheelchair Info
    "wheelchair.info.title": "Wheelchair Information",
    "wheelchair.edit.info": "Edit wheelchair information",
    "wheelchair.foldable.question": "Is your wheelchair foldable?",
    "wheelchair.foldable.status": "Foldability",
    "wheelchair.is.foldable": "Foldable",
    "wheelchair.not.foldable": "Not Foldable",
    "wheelchair.regular.dimensions": "Regular Dimensions",
    "wheelchair.folded.dimensions": "Folded Dimensions",
    "wheelchair.width": "Width",
    "wheelchair.length": "Length",
    "wheelchair.height": "Height",
    "wheelchair.weight": "Weight",
    "wheelchair.width.label": "Width (cm)",
    "wheelchair.length.label": "Length (cm)",
    "wheelchair.height.label": "Height (cm)",
    "wheelchair.weight.label": "Weight (kg)",
    "wheelchair.needs.ramp": "Needs ramp access",
    "wheelchair.needs.doorways": "Wide doorways required",

    "location.filter.recent": "Last 24 hours",
    "location.filter.all": "All time",
    "location.view.photos": "View {count} photos",

    // Routes
    "route.list.item.aria": "Route: {title}",
    "route.thumbnail.alt": "Thumbnail for {title} route",
    "route.recorded.date": "Recorded: {date}",
    "route.details": "Route Details",
    "route.from": "From",
    "route.to": "To",
    "route.recorded.date.full": "Recorded Date",
    "route.accessibility.info": "Accessibility Information",
    "route.features": "Features",

    // Reviews
    "common.write.review": "Write a Review",
    "review.title": "Write a Review",
    "review.submit": "Submit Review",
    "review.your.experience": "Your Review",
    "review.share.experience": "Share your experience...",
    "review.photos": "Photos",
    "review.add.photo": "Add Photo",

    // Location info
    "common.photos": "Photos for {name}",
    "common.photo": "{name} photo {number}",
    "common.view.photos": "View {count} photos",
    "common.see.photos": "{count} photos",

    // Accessibility Features
    "review.feature.parking": "Parking",
    "review.feature.entrance": "Main Entrance",
    "review.feature.ramp": "Ramps",
    "review.feature.pathway": "Pathways",
    "review.feature.elevator": "Elevators",
    "review.feature.restroom": "Restrooms",
    "review.feature.seating": "Seating Areas",
    "review.feature.staff": "Staff Assistance",
    "review.feature.other": "Other",

    "map.search.accessible.places": "Search accessible places",
    "map.search.result": "Search result",
    "map.search.placeholder": "Search place",
    "map.nearby.accessible.locations": "Nearby Accessible Locations",
    "map.no.accessible.locations.nearby":
      "No accessible locations found within 3km",
    "map.showing.accessible.locations.nearby":
      "Showing wheelchair accessible locations within 3km",
    "map.error.fetch.locations": "Failed to fetch nearby locations",
    "common.km": "km",
    "common.away": "away",
    "common.loading": "Loading...",

    // Location Categories
    "location.category.shoppingmall": "Shopping Mall",
    "location.category.publictransport": "Public Transport",
    "location.category.park": "Park",
    "location.category.restaurant": "Restaurant",

    // Accessibility Levels
    "accessibility.level.high": "High Accessibility",
    "accessibility.level.medium": "Medium Accessibility",
    "accessibility.level.low": "Limited Accessibility",

    // Place Categories
    "accessibility.place.shopping.mall": "Shopping Mall",
    "accessibility.place.transport.hub": "Public Transport",
    "accessibility.place.park": "Park",
    "accessibility.place.restaurant": "Restaurant",
    "accessibility.place.cafe": "Cafe",
    "accessibility.place.hotel": "Hotel",
    "accessibility.place.museum": "Museum",
    "accessibility.place.theater": "Theater",
    "accessibility.place.cinema": "Cinema",
    "accessibility.place.hospital": "Hospital",
    "accessibility.place.pharmacy": "Pharmacy",
    "accessibility.place.bank": "Bank",
    "accessibility.place.post.office": "Post Office",
    "accessibility.place.public.toilet": "Public Toilet",
    "accessibility.place.library": "Library",
    "accessibility.place.gym": "Gym",
    "accessibility.place.swimming.pool": "Swimming Pool",
    "accessibility.place.beach": "Beach",
    "accessibility.place.government.office": "Government Office",
    "accessibility.place.other": "Other Place",

    // Settings
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.accessibility": "Accessibility",
    "settings.notifications": "Notifications",
    "settings.app": "App",
    "settings.support": "Support",
    "settings.edit.profile": "Edit Profile",
    "settings.change.password": "Change Password",
    "settings.location.preferences": "Location Preferences",
    "settings.wheelchair.info": "Wheelchair Info",
    "settings.language": "Language",
    "settings.contact.support": "Contact Support",
    "settings.help.faq": "Help & FAQ",
    "settings.logout": "Log Out",
    "settings.option.aria": "{title}: {description}",
    "settings.option.title.aria": "{title}",
    "setting.location.preferences.description":
      "Set your location preferences for better route recommendations",
    "settings.wheelchair.info.description":
      "Provide information about your wheelchair for better accessibility recommendations",
    "settings.location.preferences.description":
      "Manage your location settings",
    // Auth
    "auth.login": "Sign in",
    "auth.signup": "Sign up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgot": "Forgot password?",
    "auth.continue.with": "Or continue with",
    "auth.google": "Continue with Google",
    "auth.no.account": "Do not have an account?",
    "auth.welcome": "Welcome back to {appName}!",
    "auth.remember.me": "Remember me",
    "auth.test.credentials": "Test Credentials",

    "wheelchair.notes": "Additional Notes",
    "wheelchair.notes.placeholder":
      "Record special needs or additional information you want others to know...",
    "wheelchair.notes.empty": "No additional notes",

    // Path: contexts/LanguageContext.tsx

    // ในส่วนของ translations.en ควรเพิ่มคำแปลเหล่านี้
    "common.view.written.reviews": "View written reviews",
    "common.see.all": "See all",
    "common.saving": "Saving...",
    "common.remove": "Remove",
    "common.photo.singular": "photo",
    "common.photo.plural": "photos",

    "review.feature.image.alt": "{feature} image {index}",
    "review.vote.like": "Like",
    "review.vote.dislike": "Dislike",

    "profile.my.posts": "My Posts",
    "profile.routes.library": "Route Library",
    "profile.routes.saved": "Saved Routes",
    "profile.routes.recent": "Recent Routes",
    "profile.routes.no.saved": "No saved routes yet",
    "profile.routes.no.recent": "No recent routes yet",
    "profile.no.posts.yet": "No posts yet",
    "profile.create.post": "Create a Post",
    "profile.search.posts": "Search posts",
    "profile.no.posts": "No posts found",
    "profile.no.posts.match": "No posts match your search",
    "profile.create.new.post": "Create New Post",
    "profile.basic.info": "Basic Information",
    "profile.full.name": "Full Name",
    "profile.email": "Email",
    "profile.phone": "Phone Number",
    "profile.change.photo": "Change photo",
    "profile.remove.photo": "Remove photo",
    "profile.confirm.remove.photo": "Confirm remove photo",
    "profile.confirm.remove.photo.message":
      "Are you sure you want to remove your profile photo?",

    "reviews.title": "User Reviews",
    "reviews.none": "No reviews yet",
    "reviews.sort.latest": "Latest",
    "reviews.sort.highest": "Highest Rating",
    "reviews.sort.lowest": "Lowest Rating",
    "reviews.sort.most.liked": "Most Liked",
    "reviews.written.title": "Written Reviews",
    "reviews.written.count": "written reviews",
    "reviews.count": "reviews",

    "accessibility.votes": "Accessibility Ratings",
    "accessibility.good": "Good",
    "accessibility.bad": "Bad",
    "accessibility.notsure": "Not Sure",
    "accessibility.total.votes": "Total {count} votes",
    "accessibility.photos": "Photos",

    "location.reviews": "Reviews",
    "location.details": "Details",
    "location.about": "About",
    "location.contact": "Contact Information",
    "location.phone": "Phone",
    "location.website": "Website",
    "location.hours": "Opening Hours",

    // Accessibility Statement
    "accessibility.statement": "ถ้อยแถลงการเข้าถึง",
    "accessibility.for.all": "การเข้าถึงสำหรับทุกคน",
    "accessibility.commitment": "ความมุ่งมั่นต่อการเข้าถึง",
    "accessibility.inclusive.design": "การออกแบบที่ครอบคลุม",
    "accessibility.universal.design": "การออกแบบที่เป็นสากล",
    "accessibility.standards": "มาตรฐานการเข้าถึง",
    "accessibility.compliance": "การปฏิบัติตามการเข้าถึง",
    "accessibility.screen.reader": "โปรแกรมอ่านหน้าจอ",
    "accessibility.voice.control": "การควบคุมด้วยเสียง",
    "accessibility.keyboard.navigation": "การนำทางด้วยแป้นพิมพ์",
    "accessibility.color.contrast": "ความคมชัดของสี",
    "accessibility.text.size": "ขนาดข้อความ",
    "accessibility.font.size": "ขนาดตัวอักษร",
    "accessibility.zoom": "การซูม",
    "accessibility.alternative.text": "ข้อความทางเลือก",
    "accessibility.captions": "คำบรรยาย",
    "accessibility.transcripts": "บทสนทนา",
    "accessibility.sign.language": "ภาษามือ",
    "accessibility.feedback": "ข้อเสนอแนะการเข้าถึง",
    "accessibility.report.issues": "รายงานปัญหาการเข้าถึง",
    "accessibility.features": "คุณสมบัติการเข้าถึง",
    "accessibility.limitations": "ข้อจำกัดการเข้าถึง",
    "accessibility.improvements": "การปรับปรุงการเข้าถึง",
    "accessibility.future.plans": "แผนการในอนาคตสำหรับการเข้าถึง",
    "accessibility.resources": "ทรัพยากรการเข้าถึง",
    "accessibility.testing": "การทดสอบการเข้าถึง",
    "accessibility.partners": "พันธมิตรการเข้าถึง",
    "accessibility.advocates": "ผู้สนับสนุนการเข้าถึง",
    "connection.online": "ออนไลน์",
    "connection.offline": "ออฟไลน์",
    "connection.connecting": "กำลังเชื่อมต่อ...",
    "connection.connected": "เชื่อมต่อแล้ว",
    "connection.disconnected": "ไม่ได้เชื่อมต่อ",
    "connection.lost": "การเชื่อมต่อขาดหาย",
    "connection.restored": "การเชื่อมต่อกลับคืนมาแล้ว",
    "connection.weak": "สัญญาณอ่อน",
    "connection.strong": "สัญญาณแรง",
    "connection.slow": "การเชื่อมต่อช้า",
    "connection.fast": "การเชื่อมต่อเร็ว",
    "connection.error": "ข้อผิดพลาดในการเชื่อมต่อ",
    "connection.timeout": "หมดเวลาเชื่อมต่อ",
    "connection.retry": "ลองเชื่อมต่ออีกครั้ง",
    "connection.network.unavailable": "เครือข่ายไม่พร้อมใช้งาน",
    "connection.check.network": "โปรดตรวจสอบการเชื่อมต่อของคุณ",
    "connection.wifi": "Wi-Fi",
    "connection.mobile.data": "ข้อมูลมือถือ",
    "connection.bluetooth": "บลูทูธ",
    "connection.sync": "ซิงค์",
    "connection.syncing": "กำลังซิงค์...",
    "connection.synced": "ซิงค์แล้ว",
    "connection.sync.failed": "การซิงค์ล้มเหลว",
    "connection.sync.auto": "ซิงค์อัตโนมัติ",
    "connection.sync.manual": "ซิงค์ด้วยตนเอง",
    "connection.downloading": "กำลังดาวน์โหลด...",
    "connection.uploading": "กำลังอัปโหลด...",
    "connection.download.failed": "การดาวน์โหลดล้มเหลว",
    "connection.upload.failed": "การอัปโหลดล้มเหลว",
    "connection.server.error": "ข้อผิดพลาดของเซิร์ฟเวอร์",
    "connection.client.error": "ข้อผิดพลาดของไคลเอนต์",
    "permission.location": "การเข้าถึงตำแหน่ง",
    "permission.camera": "การเข้าถึงกล้อง",
    "permission.microphone": "การเข้าถึงไมโครโฟน",
    "permission.contacts": "การเข้าถึงรายชื่อติดต่อ",
    "permission.storage": "การเข้าถึงพื้นที่จัดเก็บข้อมูล",
    "permission.notifications": "การเข้าถึงการแจ้งเตือน",
    "permission.calendar": "การเข้าถึงปฏิทิน",
    "permission.background.location": "การเข้าถึงตำแหน่งในพื้นหลัง",
    "permission.required": "จำเป็นต้องให้สิทธิ์",
    "permission.optional": "ให้สิทธิ์เพิ่มเติม",
    "permission.request": "ขอสิทธิ์",
    "permission.grant": "ให้สิทธิ์",
    "permission.denied": "สิทธิ์ถูกปฏิเสธ",
    "permission.granted": "อนุญาตแล้ว",
    "permission.revoked": "ยกเลิกการอนุญาตแล้ว",
    "permission.not.available": "ไม่สามารถเข้าถึงได้",
    "permission.settings": "ไปที่การตั้งค่า",
    "permission.explanation": "เราต้องการสิทธิ์นี้เพื่อ:",
    "permission.location.reason":
      "เพื่อแสดงตำแหน่งของคุณบนแผนที่และค้นหาเส้นทางที่เข้าถึงได้",
    "permission.camera.reason":
      "เพื่อถ่ายรูปและแชร์ข้อมูลเกี่ยวกับสถานที่และอุปสรรค",
    "permission.notification.reason":
      "เพื่อแจ้งเตือนคุณเกี่ยวกับการอัปเดตและข้อความสำคัญ",
    "permission.without.access":
      "หากไม่อนุญาต {permission} คุณจะไม่สามารถใช้งาน {feature} ได้",
    "permission.restrict": "จำกัดการเข้าถึง",
    "permission.manage": "จัดการสิทธิ์",
    "legal.terms": "ข้อกำหนดและเงื่อนไข",
    "legal.privacy": "นโยบายความเป็นส่วนตัว",
    "legal.cookies": "นโยบายคุกกี้",
    "legal.copyright": "ลิขสิทธิ์",
    "legal.rights.reserved": "สงวนลิขสิทธิ์",
    "legal.disclaimer": "ข้อสงวนสิทธิ์",
    "legal.license": "ใบอนุญาต",
    "legal.open.source": "โอเพนซอร์ส",
    "legal.credits": "เครดิต",
    "legal.attribution": "การอ้างอิง",
    "legal.data.use": "การใช้ข้อมูล",
    "legal.data.collection": "การเก็บรวบรวมข้อมูล",
    "legal.data.sharing": "การแบ่งปันข้อมูล",
    "legal.data.protection": "การคุ้มครองข้อมูล",
    "legal.user.rights": "สิทธิ์ของผู้ใช้",
    "legal.accessibility.statement": "ถ้อยแถลงการเข้าถึง",
    "legal.compliance": "การปฏิบัติตามกฎหมาย",
    "legal.report.violation": "รายงานการละเมิด",
    "legal.report.content": "รายงานเนื้อหา",
    "legal.report.abuse": "รายงานการละเมิด",
    "legal.report.violation.policy": "รายงานการละเมิดนโยบาย",
    "legal.agreement": "ข้อตกลง",
    "legal.accept": "ยอมรับ",
    "legal.decline": "ปฏิเสธ",
    "legal.agree": "ฉันยอมรับ",
    "legal.third.party": "บุคคลที่สาม",
    "legal.third.party.services": "บริการของบุคคลที่สาม",
    "legal.liability": "ความรับผิดชอบ",
    "legal.no.liability": "ไม่รับผิดชอบ",
    "legal.effective.date": "วันที่มีผลบังคับใช้",
    "legal.last.updated": "อัปเดตล่าสุด",
    "legal.version": "เวอร์ชัน",
    "app.name": "GOROLL",
    "app.slogan": "แพลตฟอร์มสำหรับการเดินทางที่เข้าถึงได้และชุมชนที่ครอบคลุม",
    "app.description":
      "GOROLL ช่วยให้ผู้ใช้รถเข็นค้นหาเส้นทางและสถานที่ที่เข้าถึงได้ แชร์ประสบการณ์กับชุมชน และเดินทางอย่างอิสระ",
    "app.version": "เวอร์ชัน {version}",
    "app.loading": "กำลังโหลด...",
    "app.initializing": "กำลังเริ่มต้น...",
    "app.updating": "กำลังอัปเดต...",
    "app.updated": "อัปเดตแล้ว",
    "app.update.available": "มีอัปเดตใหม่",
    "app.update.now": "อัปเดตเดี๋ยวนี้",
    "app.update.later": "อัปเดตภายหลัง",
    "app.feature.map": "แผนที่การเข้าถึง",
    "app.feature.routes": "เส้นทางที่เข้าถึงได้",
    "app.feature.obstacles": "รายงานอุปสรรค",
    "app.feature.community": "ชุมชนที่เข้าถึงได้",
    "app.feature.carpool": "บริการรถร่วม",
    "app.feature.reviews": "รีวิวการเข้าถึง",
    "app.feature.emergency": "ความช่วยเหลือฉุกเฉิน",
    "app.feature.profile": "โปรไฟล์ส่วนตัว",
    "app.features": "คุณสมบัติ",
    "app.benefits": "ประโยชน์",
    "app.benefit.independence": "เพิ่มความเป็นอิสระ",
    "app.benefit.confidence": "เพิ่มความมั่นใจในการเดินทาง",
    "app.benefit.community": "เชื่อมต่อกับชุมชนที่เข้าถึงได้",
    "app.benefit.awareness": "สร้างความตระหนักเกี่ยวกับการเข้าถึง",
    "app.benefit.cost": "ลดค่าใช้จ่ายในการเดินทาง",
    "app.support": "ความช่วยเหลือ",
    "app.support.center": "ศูนย์ช่วยเหลือ",
    "app.support.contact": "ติดต่อฝ่ายสนับสนุน",
    "app.support.faq": "คำถามที่พบบ่อย",
    "app.support.help": "วิธีใช้",
    "app.support.tutorial": "บทช่วยสอน",
    "app.support.community": "ชุมชนช่วยเหลือ",
    "unit.kilometer": "กิโลเมตร",
    "unit.kilometers": "กิโลเมตร",
    "unit.meter": "เมตร",
    "unit.meters": "เมตร",
    "unit.mile": "ไมล์",
    "unit.miles": "ไมล์",
    "unit.foot": "ฟุต",
    "unit.feet": "ฟุต",
    "unit.inch": "นิ้ว",
    "unit.inches": "นิ้ว",
    "unit.centimeter": "เซนติเมตร",
    "unit.centimeters": "เซนติเมตร",
    "unit.kilogram": "กิโลกรัม",
    "unit.kilograms": "กิโลกรัม",
    "unit.gram": "กรัม",
    "unit.grams": "กรัม",
    "unit.pound": "ปอนด์",
    "unit.pounds": "ปอนด์",
    "unit.hour": "ชั่วโมง",
    "unit.hours": "ชั่วโมง",
    "unit.minute": "นาที",
    "unit.minutes": "นาที",
    "unit.second": "วินาที",
    "unit.seconds": "วินาที",
    "unit.celsius": "องศาเซลเซียส",
    "unit.fahrenheit": "องศาฟาเรนไฮต์",
    "unit.km": "กม.",
    "unit.m": "ม.",
    "unit.cm": "ซม.",
    "unit.kg": "กก.",
    "unit.g": "ก.",
    "unit.hr": "ชม.",
    "unit.min": "นาที",
    "unit.sec": "วินาที",
    "unit.am": "เช้า",
    "unit.pm": "บ่าย",
    "unit.degree": "องศา",
    "unit.percent": "เปอร์เซ็นต์",
    "unit.currency.thb": "บาท",
    "unit.currency.usd": "ดอลลาร์",
    "unit.currency.symbol.thb": "฿",
    "unit.currency.symbol.usd": "$",
    "payment.method": "วิธีการชำระเงิน",
    "payment.methods": "วิธีการชำระเงิน",
    "payment.add.method": "เพิ่มวิธีการชำระเงิน",
    "payment.credit.card": "บัตรเครดิต",
    "payment.debit.card": "บัตรเดบิต",
    "payment.bank.transfer": "โอนเงินผ่านธนาคาร",
    "payment.mobile.banking": "โมบายแบงกิ้ง",
    "payment.e.wallet": "กระเป๋าเงินอิเล็กทรอนิกส์",
    "payment.cash": "เงินสด",
    "payment.paypal": "PayPal",
    "payment.process": "กำลังดำเนินการชำระเงิน",
    "payment.confirm": "ยืนยันการชำระเงิน",
    "payment.success": "การชำระเงินสำเร็จ",
    "payment.failed": "การชำระเงินล้มเหลว",
    "payment.pending": "การชำระเงินกำลังดำเนินการ",
    "payment.canceled": "การชำระเงินถูกยกเลิก",
    "payment.refund": "คืนเงิน",
    "payment.refund.requested": "ขอคืนเงินแล้ว",
    "payment.refund.processed": "ดำเนินการคืนเงินแล้ว",
    "payment.amount": "จำนวนเงิน",
    "payment.total": "ยอดรวม",
    "payment.subtotal": "ยอดรวมย่อย",
    "payment.tax": "ภาษี",
    "payment.fee": "ค่าธรรมเนียม",
    "payment.discount": "ส่วนลด",
    "payment.promo.code": "รหัสส่วนลด",
    "payment.apply.promo": "ใช้รหัสส่วนลด",
    "payment.invalid.promo": "รหัสส่วนลดไม่ถูกต้อง",
    "payment.expired.promo": "รหัสส่วนลดหมดอายุ",
    "payment.receipt": "ใบเสร็จ",
    "payment.invoice": "ใบแจ้งหนี้",
    "payment.transaction.history": "ประวัติการทำธุรกรรม",
    "payment.transaction.details": "รายละเอียดการทำธุรกรรม",
    "payment.date": "วันที่ชำระเงิน",
    "payment.card.number": "หมายเลขบัตร",
    "payment.expiry.date": "วันหมดอายุ",
    "payment.cvv": "CVV",
    "payment.card.holder": "ชื่อผู้ถือบัตร",
    "payment.save.card": "บันทึกข้อมูลบัตร",
    "payment.subscription": "การสมัครสมาชิก",
    "payment.billing.info": "ข้อมูลการเรียกเก็บเงิน",
    "payment.billing.address": "ที่อยู่สำหรับการเรียกเก็บเงิน",
    "weather.current": "สภาพอากาศปัจจุบัน",
    "weather.forecast": "พยากรณ์อากาศ",
    "weather.hourly": "รายชั่วโมง",
    "weather.daily": "รายวัน",
    "weather.temperature": "อุณหภูมิ",
    "weather.feels.like": "รู้สึกเหมือน",
    "weather.humidity": "ความชื้น",
    "weather.wind": "ลม",
    "weather.precipitation": "ปริมาณน้ำฝน",
    "weather.pressure": "ความกดอากาศ",
    "weather.visibility": "ทัศนวิสัย",
    "weather.sunrise": "พระอาทิตย์ขึ้น",
    "weather.sunset": "พระอาทิตย์ตก",
    "weather.condition.sunny": "แดดจัด",
    "weather.condition.clear": "ท้องฟ้าแจ่มใส",
    "weather.condition.partly.cloudy": "มีเมฆบางส่วน",
    "weather.condition.cloudy": "มีเมฆมาก",
    "weather.condition.overcast": "มีเมฆมืดครึ้ม",
    "weather.condition.rain": "ฝน",
    "weather.condition.light.rain": "ฝนตกเบา",
    "weather.condition.moderate.rain": "ฝนตกปานกลาง",
    "weather.condition.heavy.rain": "ฝนตกหนัก",
    "weather.condition.thunderstorm": "พายุฝนฟ้าคะนอง",
    "weather.condition.snow": "หิมะ",
    "weather.condition.fog": "หมอก",
    "weather.condition.haze": "หมอกควัน",
    "weather.condition.windy": "ลมแรง",
    "weather.air.quality": "คุณภาพอากาศ",
    "weather.air.quality.index": "ดัชนีคุณภาพอากาศ",
    "weather.air.quality.good": "ดี",
    "weather.air.quality.moderate": "ปานกลาง",
    "weather.air.quality.unhealthy.sensitive": "ไม่ดีต่อกลุ่มเสี่ยง",
    "weather.air.quality.unhealthy": "ไม่ดีต่อสุขภาพ",
    "weather.air.quality.very.unhealthy": "ไม่ดีต่อสุขภาพมาก",
    "weather.air.quality.hazardous": "อันตราย",
    "weather.alerts": "การแจ้งเตือนสภาพอากาศ",
    "weather.alert.heavy.rain": "คำเตือนฝนตกหนัก",
    "weather.alert.flood": "คำเตือนน้ำท่วม",
    "weather.alert.storm": "คำเตือนพายุ",
    "weather.alert.strong.wind": "คำเตือนลมแรง",
    "weather.alert.extreme.heat": "คำเตือนความร้อนสูง",
    "weather.alert.extreme.cold": "คำเตือนอากาศหนาวจัด",
    "media.photos": "รูปภาพ",
    "media.videos": "วิดีโอ",
    "media.take.photo": "ถ่ายรูป",
    "media.take.video": "บันทึกวิดีโอ",
    "media.choose.from.gallery": "เลือกจากแกลเลอรี",
    "media.camera": "กล้อง",
    "media.gallery": "แกลเลอรี",
    "media.crop": "ครอป",
    "media.rotate": "หมุน",
    "media.filter": "ฟิลเตอร์",
    "media.adjust": "ปรับแต่ง",
    "media.brightness": "ความสว่าง",
    "media.contrast": "ความคมชัด",
    "media.saturation": "ความอิ่มตัว",
    "media.edit": "แก้ไข",
    "media.delete": "ลบ",
    "media.share": "แชร์",
    "media.download": "ดาวน์โหลด",
    "media.save": "บันทึก",
    "media.add.caption": "เพิ่มคำบรรยาย",
    "media.add.tags": "เพิ่มแท็ก",
    "media.add.location": "เพิ่มตำแหน่ง",
    "media.playing": "กำลังเล่น",
    "media.pause": "หยุดชั่วคราว",
    "media.play": "เล่น",
    "media.stop": "หยุด",
    "media.mute": "ปิดเสียง",
    "media.unmute": "เปิดเสียง",
    "media.fullscreen": "เต็มหน้าจอ",
    "media.exit.fullscreen": "ออกจากโหมดเต็มหน้าจอ",
    "media.change.quality": "เปลี่ยนคุณภาพ",
    "media.loading": "กำลังโหลด...",
    "media.error": "เกิดข้อผิดพลาดในการโหลดสื่อ",
    "media.retry": "ลองอีกครั้ง",
    "welcome.to.goroll": "ยินดีต้อนรับสู่ GOROLL",
    "welcome.intro":
      "แพลตฟอร์มสำหรับการเดินทางที่เข้าถึงได้และชุมชนที่ครอบคลุม",
    "welcome.get.started": "เริ่มต้นใช้งาน",
    "welcome.skip": "ข้าม",
    "welcome.next": "ถัดไป",
    "welcome.back": "ย้อนกลับ",
    "welcome.finish": "เสร็จสิ้น",
    "onboarding.accessibility.options": "ตัวเลือกการเข้าถึง",
    "onboarding.setup.wheelchair": "ตั้งค่ารถเข็น",
    "onboarding.set.preferences": "ตั้งค่าการกำหนดค่า",
    "onboarding.enable.location": "เปิดใช้งานการเข้าถึงตำแหน่ง",
    "onboarding.personalize": "ปรับแต่งประสบการณ์ของคุณ",
    "onboarding.connect.friends": "เชื่อมต่อกับเพื่อน",
    "onboarding.find.accessible.places": "ค้นหาสถานที่ที่เข้าถึงได้",
    "onboarding.discover.routes": "ค้นพบเส้นทางที่สามารถเข้าถึงได้",
    "onboarding.join.community": "เข้าร่วมชุมชน",
    "onboarding.permissions": "การอนุญาต",
    "onboarding.location.access": "การเข้าถึงตำแหน่ง",
    "onboarding.camera.access": "การเข้าถึงกล้อง",
    "onboarding.notification.access": "การเข้าถึงการแจ้งเตือน",
    "onboarding.terms.of.service": "เงื่อนไขการให้บริการ",
    "onboarding.privacy.policy": "นโยบายความเป็นส่วนตัว",
    "onboarding.agree.to.terms":
      "ฉันยอมรับเงื่อนไขการให้บริการและนโยบายความเป็นส่วนตัว",
    "feedback.rate.experience": "ให้คะแนนประสบการณ์ของคุณ",
    "feedback.how.was.experience": "ประสบการณ์ของคุณเป็นอย่างไรบ้าง?",
    "feedback.leave.comment": "ฝากข้อคิดเห็น",
    "feedback.send.feedback": "ส่งข้อเสนอแนะ",
    "feedback.thank.you": "ขอบคุณสำหรับข้อเสนอแนะของคุณ",
    "feedback.improvement.suggestions": "คำแนะนำในการปรับปรุง",
    "feedback.what.liked": "คุณชอบอะไรมากที่สุด?",
    "feedback.what.disliked": "อะไรที่คุณคิดว่าเราควรปรับปรุง?",
    "feedback.report.issue": "รายงานปัญหา",
    "feedback.report.bug": "รายงานข้อบกพร่อง",
    "feedback.report.content": "รายงานเนื้อหา",
    "feedback.report.user": "รายงานผู้ใช้",
    "feedback.report.offensive": "เนื้อหาที่ไม่เหมาะสม",
    "feedback.report.inappropriate": "เนื้อหาที่ไม่เหมาะสม",
    "feedback.report.spam": "สแปม",
    "feedback.report.safety": "ปัญหาความปลอดภัย",
    "feedback.report.accessibility": "ปัญหาการเข้าถึง",
    "feedback.app.rating": "ให้คะแนนแอป",
    "feedback.location.rating": "ให้คะแนนสถานที่",
    "feedback.route.rating": "ให้คะแนนเส้นทาง",
    "feedback.driver.rating": "ให้คะแนนคนขับ",
    "feedback.passenger.rating": "ให้คะแนนผู้โดยสาร",
    "rating.excellent": "ยอดเยี่ยม",
    "rating.good": "ดี",
    "rating.average": "ปานกลาง",
    "rating.below.average": "ต่ำกว่าค่าเฉลี่ย",
    "rating.poor": "แย่",
    "rating.one.star": "1 ดาว",
    "rating.two.stars": "2 ดาว",
    "rating.three.stars": "3 ดาว",
    "rating.four.stars": "4 ดาว",
    "rating.five.stars": "5 ดาว",
    "navigation.back": "กลับ",
    "navigation.next": "ถัดไป",
    "navigation.previous": "ก่อนหน้า",
    "navigation.home": "หน้าหลัก",
    "navigation.menu": "เมนู",
    "navigation.more": "เพิ่มเติม",
    "navigation.see.all": "ดูทั้งหมด",
    "navigation.show.more": "แสดงเพิ่มเติม",
    "navigation.show.less": "แสดงน้อยลง",
    "navigation.help": "ช่วยเหลือ",
    "navigation.faq": "คำถามที่พบบ่อย",
    "navigation.support": "สนับสนุน",
    "navigation.contact.us": "ติดต่อเรา",
    "navigation.about": "เกี่ยวกับ",
    "navigation.terms": "ข้อกำหนด",
    "navigation.privacy": "ความเป็นส่วนตัว",
    "navigation.cookies": "คุกกี้",
    "navigation.language": "ภาษา",
    "navigation.close": "ปิด",
    "ui.loading": "กำลังโหลด...",
    "ui.error": "เกิดข้อผิดพลาด",
    "ui.try.again": "ลองอีกครั้ง",
    "ui.refresh": "รีเฟรช",
    "ui.success": "สำเร็จ",
    "ui.confirm": "ยืนยัน",
    "ui.cancel": "ยกเลิก",
    "ui.delete": "ลบ",
    "ui.edit": "แก้ไข",
    "ui.save": "บันทึก",
    "ui.search": "ค้นหา",
    "ui.filter": "กรอง",
    "ui.sort": "เรียง",
    "ui.share": "แชร์",
    "ui.download": "ดาวน์โหลด",
    "ui.upload": "อัปโหลด",
    "ui.add": "เพิ่ม",
    "ui.remove": "ลบออก",
    "ui.create": "สร้าง",
    "ui.update": "อัปเดต",
    "ui.select": "เลือก",
    "ui.selected": "เลือกแล้ว",
    "ui.select.all": "เลือกทั้งหมด",
    "ui.deselect.all": "ยกเลิกการเลือกทั้งหมด",
    "ui.on": "เปิด",
    "ui.off": "ปิด",
    "ui.enable": "เปิดใช้งาน",
    "ui.disable": "ปิดใช้งาน",
    "ui.enabled": "เปิดใช้งานอยู่",
    "ui.disabled": "ปิดใช้งานอยู่",
    "ui.expand": "ขยาย",
    "ui.collapse": "ย่อ",
    "ui.zoomin": "ขยายเข้า",
    "ui.zoomout": "ขยายออก",
    "ui.reset": "รีเซ็ต",
    "ui.clear": "ล้าง",
    "ui.apply": "นำไปใช้",
    "ui.done": "เสร็จสิ้น",
    "ui.skip": "ข้าม",
    "ui.continue": "ดำเนินการต่อ",
    "ui.finish": "เสร็จสิ้น",
    "ui.start": "เริ่มต้น",
    "ui.stop": "หยุด",
    "ui.pause": "หยุดชั่วคราว",
    "ui.play": "เล่น",
    "ui.resume": "ดำเนินการต่อ",
    "notification.new": "การแจ้งเตือนใหม่",
    "notification.all": "การแจ้งเตือนทั้งหมด",
    "notification.read": "อ่านแล้ว",
    "notification.unread": "ยังไม่ได้อ่าน",
    "notification.mark.read": "ทำเครื่องหมายว่าอ่านแล้ว",
    "notification.mark.all.read": "ทำเครื่องหมายว่าอ่านทั้งหมดแล้ว",
    "notification.clear.all": "ล้างทั้งหมด",
    "notification.preferences": "การตั้งค่าการแจ้งเตือน",
    "notification.push": "การแจ้งเตือนแบบผลัก",
    "notification.email": "การแจ้งเตือนทางอีเมล",
    "notification.sms": "การแจ้งเตือนทาง SMS",
    "notification.route.updates": "อัปเดตเส้นทาง",
    "notification.obstacle.reports": "รายงานอุปสรรค",
    "notification.community.activity": "กิจกรรมชุมชน",
    "notification.carpool.updates": "อัปเดตการร่วมเดินทาง",
    "notification.reminders": "การเตือน",
    "notification.emergency.alerts": "การแจ้งเตือนฉุกเฉิน",
    "message.new": "ข้อความใหม่",
    "message.reply": "ตอบกลับ",
    "message.send": "ส่ง",
    "message.typing": "กำลังพิมพ์...",
    "message.seen": "อ่านแล้ว",
    "message.sent": "ส่งแล้ว",
    "message.delivered": "ส่งถึงแล้ว",
    "message.failed": "ส่งล้มเหลว",
    "message.retry": "ลองอีกครั้ง",
    "message.attach": "แนบไฟล์",
    "message.delete": "ลบข้อความ",
    "message.no.messages": "ไม่มีข้อความ",
    "message.start.conversation": "เริ่มการสนทนา",
    "message.recent": "ล่าสุด",
    "message.search": "ค้นหาข้อความ",
    "emergency.sos": "SOS",
    "emergency.call": "โทรฉุกเฉิน",
    "emergency.medical": "เหตุฉุกเฉินทางการแพทย์",
    "emergency.police": "ตำรวจ",
    "emergency.ambulance": "รถพยาบาล",
    "emergency.fire": "ดับเพลิง",
    "emergency.share.location": "แชร์ตำแหน่งฉุกเฉิน",
    "emergency.send.alert": "ส่งการแจ้งเตือนฉุกเฉิน",
    "emergency.contacts": "ผู้ติดต่อฉุกเฉิน",
    "emergency.add.contact": "เพิ่มผู้ติดต่อฉุกเฉิน",
    "emergency.medical.info": "ข้อมูลทางการแพทย์",
    "emergency.allergies": "ภูมิแพ้",
    "emergency.medications": "ยาที่ใช้ประจำ",
    "emergency.conditions": "โรคประจำตัว",
    "emergency.blood.type": "กรุ๊ปเลือด",
    "emergency.doctor": "แพทย์ประจำตัว",
    "emergency.help.on.way": "ความช่วยเหลือกำลังมา",
    "emergency.stay.calm": "โปรดใจเย็น",
    "emergency.nearest.hospital": "โรงพยาบาลที่ใกล้ที่สุด",
    "emergency.nearest.police": "สถานีตำรวจที่ใกล้ที่สุด",
    "emergency.wheelchair.breakdown": "รถเข็นเสียหาย",
    "emergency.assist.request": "ขอความช่วยเหลือ",
    // "accessibility.feature.ramp": "ทางลาด",
    // "accessibility.feature.elevator": "ลิฟต์",
    "accessibility.feature.wide.doorway": "ประตูกว้าง",
    "accessibility.feature.accessible.restroom": "ห้องน้ำที่เข้าถึงได้",
    "accessibility.feature.accessible.parking": "ที่จอดรถสำหรับผู้พิการ",
    "accessibility.feature.braille": "อักษรเบรลล์",
    "accessibility.feature.audio.guide": "คำแนะนำเสียง",
    "accessibility.feature.service.animal": "อนุญาตให้นำสัตว์ช่วยเหลือเข้าได้",
    "accessibility.feature.staff.assistance": "มีพนักงานช่วยเหลือ",
    "accessibility.feature.wheelchair.rental": "บริการเช่ารถเข็น",
    "accessibility.feature.tactile.path": "เส้นทางสัมผัสได้",
    "accessibility.feature.handrails": "ราวจับ",
    "accessibility.feature.even.ground": "พื้นเรียบ",
    "accessibility.feature.low.counter": "เคาน์เตอร์ต่ำ",
    "accessibility.feature.automatic.door": "ประตูอัตโนมัติ",
    "accessibility.feature.accessible.seating": "ที่นั่งที่เข้าถึงได้",
    "accessibility.feature.accessible.table": "โต๊ะที่เข้าถึงได้",
    "accessibility.feature.accessible.shower": "ห้องอาบน้ำที่เข้าถึงได้",
    "accessibility.feature.accessible.bed": "เตียงที่เข้าถึงได้",
    "accessibility.feature.hearing.loop": "ระบบช่วยฟัง",
    "accessibility.feature.visual.alarm": "สัญญาณเตือนภัยแบบภาพ",
    "accessibility.feature.captioning": "คำบรรยาย",
    "error.email.required": "Email is required",
    "error.email.invalid": "Invalid email address",
    "error.password.required": "Password is required",
    "error.password.length": "Password must be at least {minLength} characters",
    "error.login.invalid": "Invalid email or password",

    // Common
    "common.yes": "Yes",
    "common.no": "No",
    "common.cancel": "Cancel",
    "common.save": "Save Changes",
    "common.save.changes": "Save Changes",
    "common.submit": "Submit",
    "common.close": "Close",
    "common.close.overlay": "Close overlay",
    "common.add.photos": "Add photos",
    "common.description": "Description",
    "common.error": "An error occurred",
    "common.cm": "cm",
    "common.kg": "kg",

    "route.recording.paused.status": "Paused",
    "route.recording.stop.confirm": "Confirm stop recording",
    "route.recording.stop.message":
      "Are you sure you want to stop recording this route?",
    "route.recording.cancel.confirm": "Confirm cancel recording",
    "route.recording.cancel.message":
      "Do you want to cancel this route recording? The route will not be saved in the system.",
    "route.recording.cancel": "Cancel recording",
    "common.continue.recording": "Continue recording",
    "route.save.title": "Save Route",
    "route.title": "Route Name",
    "route.title.placeholder":
      "Enter route name, e.g. Way home, Path to market",
    "route.description": "Description",
    "route.description.placeholder":
      "Note details about this route such as road conditions, points to be careful",
    "route.from.placeholder": "Starting point of the route, e.g. home, office",
    "route.to.placeholder": "Destination, e.g. shopping mall, school",

    "obstacle.location": "Obstacle Location",
    "location.use.current": "Use Current Location",
    "location.select.on.map": "Select on Map",
    "location.getting": "Getting location...",
    "location.error.message":
      "Could not get your current location. Please try again.",
    "location.not.supported": "Your browser does not support geolocation.",
  },
  th: {
    // Navigation
    "nav.map": "แผนที่",
    "nav.carpool": "รถร่วม",
    "nav.community": "ชุมชน",
    "nav.profile": "โปรไฟล์",

    // Map
    "map.search": "ค้นหาที่นี่...",
    "map.accessibility": "การเข้าถึง",
    "map.accessibility.fully": "เข้าถึงได้เต็มที่",
    "map.accessibility.partially": "เข้าถึงได้บางส่วน",
    "map.accessibility.limited": "เข้าถึงได้จำกัด",
    "map.locate.current.location": "ระบุตำแหน่งปัจจุบันของฉัน",
    "map.current.location": "คุณอยู่ที่นี่",
    "map.selected.route": "เส้นทางที่เลือก",
    "map.selected.route.description": "เส้นทางที่สามารถเข้าถึงได้ที่คุณเลือก",
    "map.show.route": "แสดงเส้นทาง",
    "map.route.details": "รายละเอียดเส้นทาง",
    "map.report.obstacle": "รายงานอุปสรรค",
    "map.record.route": "บันทึกเส้นทาง",
    "map.toggle.accessibility": "แสดง/ซ่อนการเข้าถึง",
    "map.route.inaccessible": "เส้นทางนี้เข้าถึงได้ยาก",
    "map.route.partially.accessible": "เส้นทางนี้เข้าถึงได้บางส่วน",
    "map.route.fully.accessible": "เส้นทางนี้เข้าถึงได้ง่าย",
    "map.emergency.button": "ปุ่มฉุกเฉิน",
    "map.emergency.call": "โทรฉุกเฉิน",
    "map.navigation.start": "เริ่มนำทาง",
    "map.navigation.end": "สิ้นสุดการนำทาง",
    "map.location.detail": "รายละเอียดสถานที่",
    "map.location.accessibility": "การเข้าถึงของสถานที่",
    "map.nearby.obstacles": "อุปสรรคใกล้เคียง",
    "map.nearby.accessible": "สถานที่เข้าถึงได้ใกล้เคียง",
    "map.filters": "ตัวกรอง",
    "map.filter.by.category": "กรองตามหมวดหมู่",
    "map.filter.by.accessibility": "กรองตามการเข้าถึง",
    "map.saved.locations": "สถานที่ที่บันทึกไว้",
    "map.recent.searches": "การค้นหาล่าสุด",
    "map.popular.destinations": "จุดหมายยอดนิยม",
    "map.share.location": "แชร์ตำแหน่ง",
    "map.get.directions": "รับเส้นทาง",
    "map.add.to.saved": "เพิ่มในรายการที่บันทึก",
    "map.remove.from.saved": "นำออกจากรายการที่บันทึก",
    "map.report.issue": "รายงานปัญหา",
    "map.suggest.edit": "แนะนำการแก้ไข",
    "map.view.routes": "ดูเส้นทาง",
    "map.accessible.entrance": "ทางเข้าที่เข้าถึงได้",
    "map.accessible.restroom": "ห้องน้ำที่เข้าถึงได้",
    "map.accessible.parking": "ที่จอดรถที่เข้าถึงได้",
    "map.elevator": "ลิฟต์",
    "map.ramp": "ทางลาด",

    // Accessibility Features
    "review.feature.parking": "ที่จอดรถ",
    "review.feature.entrance": "ทางเข้าหลัก",
    "review.feature.ramp": "ทางลาด",
    "review.feature.pathway": "ทางเดิน",
    "review.feature.elevator": "ลิฟต์",
    "review.feature.restroom": "ห้องน้ำ",
    "review.feature.seating": "พื้นที่นั่ง",
    "review.feature.staff": "พนักงานช่วยเหลือ",
    "review.feature.other": "อื่นๆ",

    // Place Categories
    "accessibility.place.shopping.mall": "ห้างสรรพสินค้า",
    "accessibility.place.transport.hub": "ระบบขนส่งสาธารณะ",
    "accessibility.place.park": "สวนสาธารณะ",
    "accessibility.place.restaurant": "ร้านอาหาร",
    "accessibility.place.cafe": "คาเฟ่",
    "accessibility.place.hotel": "โรงแรม",
    "accessibility.place.museum": "พิพิธภัณฑ์",
    "accessibility.place.theater": "โรงละคร",
    "accessibility.place.cinema": "โรงภาพยนตร์",
    "accessibility.place.hospital": "โรงพยาบาล",
    "accessibility.place.pharmacy": "ร้านขายยา",
    "accessibility.place.bank": "ธนาคาร",
    "accessibility.place.post.office": "ที่ทำการไปรษณีย์",
    "accessibility.place.public.toilet": "ห้องน้ำสาธารณะ",
    "accessibility.place.library": "ห้องสมุด",
    "accessibility.place.gym": "ยิม",
    "accessibility.place.swimming.pool": "สระว่ายน้ำ",
    "accessibility.place.beach": "ชายหาด",
    "accessibility.place.government.office": "สำนักงานราชการ",
    "accessibility.place.other": "สถานที่อื่นๆ",

    // Obstacle-related translations
    "obstacle.status.active": "ยังอยู่",
    "obstacle.status.resolved": "แก้ไขแล้ว",
    "obstacle.reported.by": "รายงานโดย: {name}",
    "obstacle.reported.date": "วันที่: {date}",
    "obstacle.last.verified": "ตรวจสอบล่าสุด: {date}",
    "obstacle.verify.status.title": "ยืนยันสถานะ",
    "obstacle.verify.status.description":
      "ช่วยอัพเดทข้อมูลโดยการยืนยันอุปสรรคนี้",
    "obstacle.verify.still.present": "ยังมีอยู่",
    "obstacle.verify.no.longer.present": "ไม่มีแล้ว",
    "obstacle.category.sidewalk_issues": "ปัญหาทางเท้า",
    "obstacle.category.permanent_obstacles": "อุปสรรคถาวร",
    "obstacle.category.temporary_obstacles": "อุปสรรคชั่วคราว",
    "obstacle.category.connection_issues": "ปัญหาการเชื่อมต่อ",
    "obstacle.category.safety_issues": "ปัญหาความปลอดภัย",
    "obstacle.category.etc": "อื่นๆ",
    "obstacle.report.title": "รายงานอุปสรรค",
    "obstacle.report.details": "รายละเอียดอุปสรรค",
    "obstacle.report.category": "หมวดหมู่",
    "obstacle.report.type": "ประเภทของอุปสรรค",
    "obstacle.report.description": "คำอธิบาย",
    "obstacle.report.submit": "ส่งรายงาน",
    "obstacle.type.rough_surface": "พื้นผิวไม่เรียบ/เสียหาย",
    "obstacle.type.broken_drain": "ท่อระบายน้ำชำรุด/ฝาท่อหาย",
    "obstacle.type.flooding": "น้ำท่วมขัง",
    "obstacle.type.steep_slope": "ทางลาดชันเกินไป",
    "obstacle.type.narrow_path": "ทางแคบเกินไป",
    "obstacle.type.no_ramp": "ไม่มีทางลาด",
    "obstacle.type.utility_pole": "เสาไฟฟ้า/ป้าย",
    "obstacle.type.tree": "ต้นไม้/กระถางต้นไม้",
    "obstacle.type.bus_stop": "ป้ายรถเมล์/ที่พักรถเมล์",
    "obstacle.type.construction": "การก่อสร้าง",
    "obstacle.type.parked_car": "รถจอดบนทางเท้า",
    "obstacle.type.parked_motorcycle": "มอเตอร์ไซค์บนทางเท้า",
    "obstacle.type.mobile_vendor": "ร้านค้าเคลื่อนที่",
    "obstacle.type.construction_material": "วัสดุก่อสร้าง",
    "obstacle.type.fallen_wire": "สายไฟตก",
    "obstacle.photos.add": "เพิ่มรูปถ่าย",
    "obstacle.photo.selected": "รูปที่เลือก {number}",
    "obstacle.description.placeholder":
      "อธิบายเพิ่มเติมเกี่ยวกับอุปสรรคที่พบ...",
    "obstacle.photos.click.to.add": "คลิกเพื่อเพิ่มรูปถ่าย",
    "obstacle.location.add": "เพิ่มตำแหน่ง",
    "obstacle.thanks.for.reporting": "ขอบคุณสำหรับการรายงาน",

    // Actions
    "action.record.route": "บันทึกเส้นทาง",
    "action.report.obstacle": "รายงานอุปสรรค",
    "action.add.post": "เพิ่มโพสต์",

    // Carpool
    "carpool.title": "รถร่วม",
    "carpool.available.rides": "รถที่ว่างอยู่",
    "carpool.my.rides": "การเดินทางของฉัน",
    "carpool.from": "จาก:",
    "carpool.to": "ถึง:",
    "carpool.more.info": "ข้อมูลเพิ่มเติม",
    "carpool.ride.details": "รายละเอียดการเดินทาง",
    "carpool.vehicle.info": "ข้อมูลยานพาหนะ",
    "carpool.price.per.seat": "ราคาต่อที่นั่ง",
    "carpool.chat.with.driver": "แชทกับคนขับ",
    "carpool.book.now": "จองตอนนี้",
    "carpool.messages": "ข้อความ",
    "carpool.driver": "คนขับ",
    "carpool.seats.available": "ที่นั่งว่าง {count} ที่",
    "carpool.date": "วันที่",
    "carpool.time": "เวลา",
    "carpool.vehicle.type": "ประเภทยานพาหนะ",
    "carpool.rating": "คะแนน",
    "carpool.offer.ride": "เสนอการเดินทาง",
    "carpool.find.ride": "ค้นหาการเดินทาง",
    "carpool.ride.history": "ประวัติการเดินทาง",
    "carpool.upcoming.rides": "การเดินทางที่จะถึง",
    "carpool.past.rides": "การเดินทางที่ผ่านมา",
    "carpool.vehicle.details": "รายละเอียดยานพาหนะ",
    "carpool.wheelchair.support": "รองรับรถเข็น",
    "carpool.accessibility.features": "คุณสมบัติการเข้าถึง",
    "carpool.booking.confirmed": "ยืนยันการจองแล้ว",
    "carpool.booking.pending": "การจองกำลังรอการยืนยัน",
    "carpool.booking.cancelled": "การจองถูกยกเลิก",
    "carpool.contact.driver": "ติดต่อคนขับ",
    "carpool.payment.method": "วิธีการชำระเงิน",
    "carpool.payment.amount": "จำนวนเงิน",
    "carpool.payment.details": "รายละเอียดการชำระเงิน",
    "carpool.add.payment.method": "เพิ่มวิธีการชำระเงิน",
    "carpool.driver.rating": "คะแนนของคนขับ",
    "carpool.passenger.rating": "คะแนนของผู้โดยสาร",
    "carpool.message.driver": "ส่งข้อความถึงคนขับ",
    "carpool.message.passenger": "ส่งข้อความถึงผู้โดยสาร",
    "carpool.no.available.rides": "ไม่มีการเดินทางที่ว่างอยู่",
    "carpool.search.rides": "ค้นหาการเดินทาง",

    // Community
    "community.search": "ค้นหาที่นี่...",
    "community.categories.all": "ทั้งหมด",
    "community.categories.guides": "คู่มือและเคล็ดลับ",
    "community.categories.equipment": "รีวิวอุปกรณ์",
    "community.categories.stories": "เรื่องราวแรงบันดาลใจ",
    "community.categories.news": "ข่าวสารและกิจกรรม",
    "community.categories.services": "บริการให้ความช่วยเหลือ",
    "community.categories.routes": "แผนเดินทางแนะนำ",
    "community.categories.health": "สุขภาพและการดูแลตัวเอง",
    "community.categories.career": "อาชีพและการทำงาน",
    "community.post": "โพสต์",
    "community.create.post": "สร้างโพสต์",
    "community.share": "แชร์",
    "community.add.location": "เพิ่มตำแหน่งที่ตั้ง",
    "community.no.posts": "ไม่พบโพสต์",
    "community.post.view.details": "ดูรายละเอียดโพสต์",
    "community.post.image.alt": "รูปภาพโพสต์โดย {username}",
    "community.user.avatar": "รูปประจำตัวของ {username}",
    "community.post.like": "ถูกใจโพสต์",
    "community.post.comments": "ดูความคิดเห็น",
    "community.post.share": "แชร์โพสต์",
    "community.add.comment": "เพิ่มความคิดเห็น...",
    "community.sort.by": "เรียงตาม",
    "community.most.recent": "ล่าสุด",
    "community.most.liked": "ถูกใจมากที่สุด",
    "community.most.comments": "ความคิดเห็นมากที่สุด",
    "community.filter.features": "คุณสมบัติการเข้าถึง",
    "community.post.title": "หัวข้อโพสต์",
    "community.post.content": "เนื้อหาโพสต์",
    "community.post.category": "หมวดหมู่",
    "community.post.photos": "รูปภาพ",
    "community.post.videos": "วิดีโอ",
    "community.post.tags": "แท็ก",
    "community.post.date": "วันที่",
    "community.post.author": "ผู้เขียน",
    "community.post.accessibility.features": "คุณสมบัติการเข้าถึง",
    "community.post.write.title": "เขียนหัวข้อ...",
    "community.post.write.experience": "แชร์ประสบการณ์ของคุณ...",
    "community.post.select.category": "เลือกหมวดหมู่",
    "community.post.upload.photos": "อัพโหลดรูปภาพ",
    "community.post.success": "โพสต์สำเร็จแล้ว",
    "community.comment.reply": "ตอบกลับ",
    "community.comment.delete": "ลบความคิดเห็น",
    "community.comment.report": "รายงานความคิดเห็น",
    "community.trending": "กำลังเป็นที่นิยม",
    "community.featured": "แนะนำ",
    "community.following": "กำลังติดตาม",
    "community.my.posts": "โพสต์ของฉัน",
    "community.saved.posts": "โพสต์ที่บันทึกไว้",

    // Profile
    "profile.edit": "แก้ไขโปรไฟล์",
    "profile.routes": "เส้นทาง",
    "profile.following": "กำลังติดตาม",
    "profile.followers": "ผู้ติดตาม",
    "profile.wheelchair.info": "ข้อมูลรถเข็น",
    "profile.tabs.all": "เส้นทางทั้งหมด",
    "profile.tabs.recorded": "ที่บันทึก",
    "profile.tabs.saved": "ที่บันทึกไว้",
    "profile.settings": "การตั้งค่า",

    // Wheelchair Info
    "wheelchair.info.title": "ข้อมูลรถเข็น",
    "wheelchair.edit.info": "แก้ไขข้อมูลรถเข็น",
    "wheelchair.foldable.question": "รถเข็นของคุณพับได้หรือไม่?",
    "wheelchair.foldable.status": "ความสามารถในการพับ",
    "wheelchair.is.foldable": "พับได้",
    "wheelchair.not.foldable": "พับไม่ได้",
    "wheelchair.regular.dimensions": "ขนาดปกติ",
    "wheelchair.folded.dimensions": "ขนาดเมื่อพับ",
    "wheelchair.width": "ความกว้าง",
    "wheelchair.length": "ความยาว",
    "wheelchair.height": "ความสูง",
    "wheelchair.weight": "น้ำหนัก",
    "wheelchair.width.label": "ความกว้าง (ซม.)",
    "wheelchair.length.label": "ความยาว (ซม.)",
    "wheelchair.height.label": "ความสูง (ซม.)",
    "wheelchair.weight.label": "น้ำหนัก (กก.)",
    "wheelchair.needs.ramp": "ต้องการทางลาด",
    "wheelchair.needs.doorways": "ต้องการประตูกว้าง",

    // Routes
    "route.list.item.aria": "เส้นทาง: {title}",
    "route.thumbnail.alt": "ภาพย่อสำหรับเส้นทาง {title}",
    "route.recorded.date": "บันทึกเมื่อ: {date}",
    "route.details": "รายละเอียดเส้นทาง",
    "route.from": "จาก",
    "route.to": "ถึง",
    "route.recorded.date.full": "วันที่บันทึก",
    "route.accessibility.info": "ข้อมูลการเข้าถึง",
    "route.features": "คุณสมบัติ",
    "route.distance": "ระยะทาง",
    "route.duration": "ระยะเวลา",
    "route.accessibility.high": "การเข้าถึงสูง",
    "route.accessibility.medium": "การเข้าถึงปานกลาง",
    "route.accessibility.low": "การเข้าถึงต่ำ",
    "route.recording.start": "เริ่มการบันทึก",
    "route.recording.pause": "หยุดการบันทึกชั่วคราว",
    "route.recording.resume": "บันทึกต่อ",
    "route.recording.stop": "หยุดการบันทึก",
    "route.recording.save": "บันทึกเส้นทาง",
    "route.recording.discard": "ยกเลิกการบันทึก",
    "route.recording.in.progress": "กำลังบันทึก...",
    "route.share": "แชร์เส้นทาง",
    "route.edit": "แก้ไขเส้นทาง",
    "route.delete": "ลบเส้นทาง",
    "route.recording.name.route": "ตั้งชื่อเส้นทาง",
    "route.add.description": "เพิ่มคำอธิบาย",
    "route.library": "คลังเส้นทาง",
    "route.my.routes": "เส้นทางของฉัน",
    "route.community.routes": "เส้นทางในชุมชน",
    "route.popular.routes": "เส้นทางยอดนิยม",
    "route.recent.routes": "เส้นทางล่าสุด",

    "ui.select": "เลือก",
    "ui.select.category": "เลือกหมวดหมู่",
    "ui.select.type": "เลือกประเภท",

    "community.categories.accessible_place": "สถานที่ที่เข้าถึงได้",
    "community.categories.question": "คำถาม",
    "media.photo.selected": "รูปที่เลือก {number}",
    "media.photos.add": "เพิ่มรูปภาพหรือวิดีโอ",

    // Reviews
    "common.write.review": "เขียนรีวิว",
    "review.title": "เขียนรีวิว",
    "review.submit": "ส่งรีวิว",
    "review.your.experience": "รีวิวของคุณ",
    "review.share.experience": "แชร์ประสบการณ์ของคุณ...",
    "review.photos": "รูปภาพ",
    "review.add.photo": "เพิ่มรูปภาพ",
    "review.accessibility.features": "คุณสมบัติการเข้าถึง",
    "review.accessibility.rating": "คะแนนการเข้าถึง",
    "review.vote.like": "ชอบ",
    "review.vote.dislike": "ไม่ชอบ",
    "review.vote.not.sure": "ไม่แน่ใจ",
    "review.add.photos.of": "เพิ่มรูปภาพของ {feature}",
    "review.thanks.for.review": "ขอบคุณสำหรับการรีวิว",
    "review.location": "สถานที่",
    "review.date": "วันที่",
    "review.rating": "คะแนน",
    "review.comments": "ความคิดเห็น",

    "map.search.accessible.places": "ค้นหาสถานที่ที่เข้าถึงได้",
    "map.search.result": "ผลการค้นหา",
    "map.nearby.accessible.locations": "สถานที่ใกล้เคียงที่เข้าถึงได้",
    "map.no.accessible.locations.nearby":
      "ไม่พบสถานที่ที่เข้าถึงได้ในระยะ 3 กม.",
    "map.showing.accessible.locations.nearby":
      "กำลังแสดงสถานที่ที่เข้าถึงได้ด้วยรถเข็นในระยะ 3 กม.",
    "map.error.fetch.locations": "ไม่สามารถดึงข้อมูลสถานที่ใกล้เคียงได้",
    "common.km": "กม.",
    "common.away": "ห่างออกไป",
    "common.loading": "กำลังโหลด...",

    // Location Categories
    "location.category.shoppingmall": "ห้างสรรพสินค้า",
    "location.category.publictransport": "ขนส่งสาธารณะ",
    "location.category.park": "สวนสาธารณะ",
    "location.category.restaurant": "ร้านอาหาร",

    // Accessibility Levels
    "accessibility.level.high": "เข้าถึงได้ง่าย",
    "accessibility.level.medium": "เข้าถึงได้ปานกลาง",
    "accessibility.level.low": "เข้าถึงได้จำกัด",

    "map.search.placeholder": "ค้นหาสถานที่ที่เข้าถึงได้...",

    // Common
    "common.yes": "ใช่",
    "common.no": "ไม่",
    "common.cancel": "ยกเลิก",
    "common.save": "บันทึกการเปลี่ยนแปลง",
    "common.save.changes": "บันทึกการเปลี่ยนแปลง",
    "common.submit": "ส่ง",
    "common.close": "ปิด",
    "common.close.overlay": "ปิดหน้าต่าง",
    "common.add.photos": "เพิ่มรูปภาพ",
    "common.description": "รายละเอียด",

    "common.error": "เกิดข้อผิดพลาด",
    "common.cm": "ซม.",
    "common.kg": "กก.",
    "common.photos": "รูปภาพของ {name}",
    "common.photo": "รูปภาพ {name} ที่ {number}",
    "common.view.photos": "ดู {count} รูปภาพ",

    "wheelchair.notes": "บันทึกเพิ่มเติม",
    "wheelchair.notes.placeholder":
      "บันทึกความต้องการพิเศษหรือข้อมูลเพิ่มเติมที่ต้องการให้ผู้อื่นทราบ...",
    "wheelchair.notes.empty": "ไม่มีบันทึกเพิ่มเติม",

    // Settings
    "settings.title": "การตั้งค่า",
    "settings.account": "บัญชี",
    "settings.accessibility": "การเข้าถึง",
    "settings.notifications": "การแจ้งเตือน",
    "settings.app": "แอป",
    "settings.support": "ความช่วยเหลือ",
    "settings.edit.profile": "แก้ไขโปรไฟล์",
    "settings.change.password": "เปลี่ยนรหัสผ่าน",
    "settings.location.preferences": "การตั้งค่าตำแหน่ง",
    "settings.location.preferences.description":
      "จัดการการตั้งค่าตำแหน่งของคุณ",
    "settings.wheelchair.info": "ข้อมูลรถเข็น",
    "settings.wheelchair.info.description": "อัปเดตรายละเอียดรถเข็นของคุณ",
    "settings.language": "ภาษา",
    "settings.contact.support": "ติดต่อฝ่ายสนับสนุน",
    "settings.help.faq": "ช่วยเหลือและคำถามที่พบบ่อย",
    "settings.logout": "ออกจากระบบ",

    "location.filter.recent": "24 ชั่วโมงล่าสุด",
    "location.filter.all": "ทั้งหมด",
    "location.view.photos": "ดู {count} รูปภาพ",

    // ในส่วนของ translations.th ควรเพิ่มคำแปลภาษาไทยดังนี้
    "common.view.written.reviews": "ดูรีวิวแบบข้อความ",
    "common.see.all": "ดูทั้งหมด",
    "common.saving": "กำลังบันทึก...",
    "common.remove": "ลบ",
    "common.photo.singular": "รูปภาพ",
    "common.photo.plural": "รูปภาพ",
    "common.see.photos": "{count} รูปภาพ",

    "review.feature.image.alt": "รูปภาพ {feature} ที่ {index}",

    "profile.my.posts": "โพสต์ของฉัน",
    "profile.routes.library": "ไลบรารีเส้นทาง",
    "profile.routes.saved": "เส้นทางที่บันทึก",
    "profile.routes.recent": "เส้นทางล่าสุด",
    "profile.routes.no.saved": "ยังไม่มีเส้นทางที่บันทึกไว้",
    "profile.routes.no.recent": "ยังไม่มีเส้นทางที่ใช้ล่าสุด",
    "profile.no.posts.yet": "ยังไม่มีโพสต์",
    "profile.create.post": "สร้างโพสต์",
    "profile.search.posts": "ค้นหาโพสต์",
    "profile.no.posts": "ไม่พบโพสต์",
    "profile.no.posts.match": "ไม่พบโพสต์ที่ตรงกับการค้นหา",
    "profile.create.new.post": "สร้างโพสต์ใหม่",
    "profile.basic.info": "ข้อมูลพื้นฐาน",
    "profile.full.name": "ชื่อ-นามสกุล",
    "profile.email": "อีเมล",
    "profile.phone": "เบอร์โทรศัพท์",
    "profile.change.photo": "เปลี่ยนรูปโปรไฟล์",
    "profile.remove.photo": "ลบรูปโปรไฟล์",
    "profile.confirm.remove.photo": "ยืนยันการลบรูปโปรไฟล์",
    "profile.confirm.remove.photo.message":
      "คุณแน่ใจหรือไม่ว่าต้องการลบรูปโปรไฟล์นี้?",

    "reviews.title": "รีวิวจากผู้ใช้",
    "reviews.none": "ยังไม่มีรีวิว",
    "reviews.sort.latest": "ล่าสุด",
    "reviews.sort.highest": "คะแนนสูงสุด",
    "reviews.sort.lowest": "คะแนนต่ำสุด",
    "reviews.sort.most.liked": "ถูกใจมากที่สุด",
    "reviews.written.title": "รีวิวแบบข้อความ",
    "reviews.written.count": "รีวิวแบบข้อความ",
    "reviews.count": "รีวิว",

    "accessibility.votes": "การประเมินการเข้าถึง",
    "accessibility.good": "ดี",
    "accessibility.bad": "ไม่ดี",
    "accessibility.notsure": "ไม่แน่ใจ",
    "accessibility.total.votes": "ทั้งหมด {count} โหวต",
    "accessibility.photos": "รูปภาพ",

    "location.reviews": "รีวิว",
    "location.details": "รายละเอียด",
    "location.about": "เกี่ยวกับสถานที่",
    "location.contact": "ข้อมูลติดต่อ",
    "location.phone": "โทรศัพท์",
    "location.website": "เว็บไซต์",
    "location.hours": "เวลาเปิด-ปิด",

    "route.recording.paused.status": "หยุดชั่วคราว",
    "route.recording.stop.confirm": "ยืนยันการหยุดบันทึกเส้นทาง",
    "route.recording.stop.message":
      "คุณแน่ใจหรือไม่ว่าต้องการหยุดการบันทึกเส้นทางนี้?",
    "route.recording.cancel.confirm": "ยืนยันการยกเลิกการบันทึกเส้นทาง",
    "route.recording.cancel.message":
      "คุณต้องการยกเลิกการบันทึกเส้นทางนี้หรือไม่? เส้นทางจะไม่ถูกบันทึกในระบบ",
    "route.recording.cancel": "ยกเลิกการบันทึก",
    "common.continue.recording": "ดำเนินการบันทึกต่อ",
    "route.save.title": "บันทึกเส้นทาง",
    "route.title": "ชื่อเส้นทาง",
    "route.title.placeholder": "ใส่ชื่อเส้นทาง เช่น ทางกลับบ้าน, เส้นทางไปตลาด",
    "route.description": "รายละเอียด",
    "route.description.placeholder":
      "บันทึกรายละเอียดเกี่ยวกับเส้นทางนี้ เช่น สภาพถนน จุดที่ต้องระวัง",
    "route.from.placeholder": "จุดเริ่มต้นของเส้นทาง เช่น บ้าน, ที่ทำงาน",
    "route.to.placeholder": "จุดหมายปลายทาง เช่น ห้างสรรพสินค้า, โรงเรียน",

    "obstacle.location": "ตำแหน่งอุปสรรค",
    "location.use.current": "ใช้ตำแหน่งปัจจุบัน",
    "location.select.on.map": "เลือกบนแผนที่",
    "location.getting": "กำลังรับตำแหน่ง...",
    "location.error.message":
      "ไม่สามารถรับตำแหน่งปัจจุบันได้ กรุณาลองใหม่อีกครั้ง",
    "location.not.supported": "เบราว์เซอร์ของคุณไม่รองรับการรับตำแหน่ง",
  },
};

// Language provider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  // Get initial language from local storage or default to English
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const savedLanguage = localStorage.getItem("language") as Language;
      return savedLanguage && (savedLanguage === "en" || savedLanguage === "th")
        ? savedLanguage
        : "en";
    }
    return "en";
  });

  // Persist language selection to local storage
  useEffect(() => {
    localStorage.setItem("language", language);
    // Update html lang attribute
    document.documentElement.lang = language;
  }, [language]);

  // Function to set language
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  // Enhanced translation function with optional parameter interpolation
  const t: TranslationFunction = (
    key: string,
    params?: Record<string, string | number>
  ): string => {
    const translation = translations[language][key] || key;
    return interpolate(translation, params);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = () => useContext(LanguageContext);
